name: Build Armbian Desktop
on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: armbian/build@v25.05
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_target: "build"
          armbian_board: "radxa-cubie-a5e"
          armbian_kernel_branch: "current"
          armbian_release: "bookworm"
          armbian_ui: "xfce"
          
