name: Build Armbian Desktop
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "radxa-cubie-a5e"
          armbian_kernel_branch: "current"
          armbian_release: "bookworm"
          armbian_ui: "xfce"
